import Head from 'next/head'
import Link from "next/link"
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {GraphQLClient, gql} from 'graphql-request';
import BlogCard from '../../components/BlogCard';

const inter = Inter({ subsets: ['latin'] });

const graphcms = new GraphQLClient("https://api-eu-west-2.hygraph.com/v2/clg7po9uz1fyp01ui7f8og5z5/master");

const QUERY = gql`
    {
      posts{
        id,
        title,
        datePublished,
        slug,
        content{
          html
        }
        author{
          name,
          avatar{
            url
          }
        }
        coverPhoto{
            url
        }
      }
    }
`;

export async function getStaticProps() {
  const {posts} = await graphcms.request(QUERY);
  return{
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Blog Hive</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.nav}>
       <Link className={styles.logo} href={"/"}> Blog Hive</Link>
     </div>
      <main className={styles.main}>
        {posts.map((post) => (
          <BlogCard 
            title={post.title} 
            author={post.author} 
            coverPhoto={post.coverPhoto} 
            key={post.id} 
            datePublished={post.datePublished} 
            slug={post.slug}
          />
        ))}
      </main>
    </>
  )
}


